### ISSUE TITLE
Dedicated Server crash when placing flatscreens.

### ISSUE THREAD

**Issue by UniversalMigrator** [ben-mkiv/OCDevices#1]
Dedicated server crashes when placing a flatscreen in world. Server will continue to crash when server reloads. Crash log: https://pastebin.com/NtzVczsK

Using forge-1.12.2-14.23.5.2796 and version 20190116 of this mod.

**Comment by ben-mkiv** [comment]
Thanks for the report.

Fixed version is on curseForge => https://minecraft.curseforge.com/projects/ocdevices/files
