### ISSUE TITLE
[Bug] Client Crash on place Bridge on Wall

### ISSUE THREAD

**Issue by bimbam2103** [ben-mkiv/OCDevices#11]
**Describe the bug**
If i place a bridge on a wall the Client crashs. Server runs normally.

**To Reproduce**
1. Start multiplayer server
2. Start client
3. get bridge
4. place it on wall
5. See error

**Expected behavior**
The bridge should be placed without client crash

**Screenshots / Code Snippet**
If applicable, add the code you used and screenshots of how your setup looks like
[crash-2020-03-09_23.12.29-client.txt](https://github.com/ben-mkiv/OCDevices/files/4309190/crash-2020-03-09_23.12.29-client.txt)

**Minecraft:**
 - OCDevices 1.0.0-44
 - 1.12.2
 - Forge 1.12.2 latest 14.23.5.2847

**Additional context**
After restart of the client the block exists on a wall without any issues and can be used

If you need to check some other coexisting mods: https://www.technicpack.net/modpack/kingdom-of-bimbam.1626408

**Comment by ben-mkiv** [comment]
thanks for reporting the issue, this build should fix the issue
https://ci.pc-logix.com/job/OCDevices/45/artifact/build/libs/ocdevices-MC1.12.2-1.0.0-45.jar

**Comment by bimbam2103** [comment]
> 
> 
> thanks for reporting the issue, this build should fix the issue
> https://ci.pc-logix.com/job/OCDevices/45/artifact/build/libs/ocdevices-MC1.12.2-1.0.0-45.jar

This fixed the issue. Thank you for your response.

Greetings
