### ISSUE TITLE
Make Case Tier a config option

### ISSUE THREAD

**Issue by ben-mkiv** [ben-mkiv/OCDevices#3]
so we can default the 5150 to tier1

**Comment by ben-mkiv** [comment]
done in dev

**Comment by ben-mkiv** [comment]
but the recipes... have to think of another way to solve this, probably craft everything as tier1 and use upgrades to change the cases tier

**Comment by zenith391** [comment]
I think it would be better to change tier 3 computer in the recipe to an other tier computer. The resulting computer will be of the tier of the recipe.
Example: I craft the NEXT case with a tier2 computer, i get a tier2 NEXT case

**Comment by ben-mkiv** [comment]
this is already fixed in dev, but cant give a ETA for a new release on curseforge yet as i want to finish some other things before.

new Cases are always tier1 now and you can upgrade them by rightclicking them with a (new) upgrade item. (also added a blast resistance upgrade)

**Comment by zenith391** [comment]
Ok, however i think that changing the resulting tier by crafting was easier to understand
